const articles = [
  {
    name: "Vellattu Kannazhagi Song Lyrics",
    title: "Vellattu Kannazhagi Song Lyrics",
    content: [
      "Singer: Sean Roldan",
      "Music by: Sean Roldan",
      "Chorus:",
      "Thananae thana nae naanaa naa",
      "Thananae thana nae naanaa naa",
      "Thaana naa thaananaa ooo hooo",
      "Thaana naa thaananaa ooo hooo",
      "Hooo ooo hoo oooo",
      "Hooo ooo hoo oooo",
      "",
      "Male: Vellaattu kannazhagi",
      "Vennaikatti pal azhagi",
      "Ooranna oorukulla padai edutha",
      "",
      "Male: Kaanatha kattazhagi",
      "Kaattumalli settazhagi",
      "Paambaaga nenjukulla padamedutha",
      "",
      "Male: Vellaattu kannazhagi",
      "Vennaikatti pal azhagi",
      "Ooranna oorukulla padai edutha",
      "",
      "Male: Kaanatha kattazhagi",
      "Kaattumalli settazhagi",
      "Paambaaga nenjukulla padamedutha",
      "",
      "Male: Pesaamalae",
      "Enna vaatti edutha",
      "Kaththi veesamalae",
      "Pala kaayam kodutha",
      "",
      "Male: Vaatti edutha",
      "Pala kaayam kodutha",
      "Vaatti edutha",
      "Pala kaayam kodutha",
      "",
      "Male: Ohooo ooo ooo ooo",
      "Ohoo ooo ooo",
      "Ohooo ooo ooo ooo",
      "Ohoo ooo ooo",
      "",
      "Male & Female:",
      "Hooo ooo hoo oooo",
      "Hooo ooo hoo oooo",
      "",
      "Male: Ponnae illa",
      "Iva rosa kudam",
      "Kannae moodama",
      "Naan paarthu paaratidum",
      "Nalla kaadhal padam",
      "",
      "Male: Hey poiyae illa",
      "Iva koyil ratham",
      "Oththa parvaikku munnala",
      "Ennagummo intha saathi madham",
      "",
      "Male: Oh naadu nagaram",
      "Ariyaa azhaga",
      "Kaatturalae dhinusa",
      "Aasai manasa housefullaaga",
      "Aanenae naan circus-ah",
      "",
      "Male: Vellaattu kannazhagi",
      "Vennaikatti pal azhagi",
      "",
      "Male: Vellaattu kannazhagi",
      "Vennaikatti pal azhagi",
      "Ooranna oorukulla padai edutha",
      "",
      "Male: Kaanatha kattazhagi",
      "Kaattumalli settazhagi",
      "Paambaaga nenjukulla padamedutha",
      "",
      "Chorus:",
      "Thananae thana nae naanaa naa",
      "Thananae thana nae naanaa naa",
      "Thaana naa thaananaa ooo hooo",
      "Thaana naa thaananaa ooo hooo",
      "Male & Female: Hooo ooo hoo oooo",
      "Hooo ooo hoo oooo",
      "",
      "Male: Jillavukkae",
      "Ava mela kannu",
      "Vanthu munnalae ninnalae",
      "Naan theduren ennai kaanumennu",
      "",
      "Male: Hmm ellarukkum ava heroine",
      "Sandhu bondhelaam",
      "Villangal ninnalumae",
      "Love-eh kaapen ninnu",
      "",
      "Male: Oh oooo oorum theruvum",
      "Kedayaa kedakka",
      "Yaara paappaa thirumbi",
      "Koona sirippil kenayan aagi",
      "Ponenae naan kulambi",
      "",
      "Male: Vellaattu kannazhagi",
      "Vennaikatti pal azhagi",
      "Ooranna oorukulla padai edutha",
      "",
      "Male: Kaanatha kattazhagi",
      "Kaattumalli settazhagi",
      "Paambaaga nenjukulla padamedutha",
      "",
      "Male: Pesaamalae",
      "Enna vaatti edutha",
      "Kaththi veesamalae",
      "Pala kaayam kodutha",
      "",
      "Male: Vaatti edutha",
      "Pala kaayam kodutha",
      "Vaatti edutha",
      "Pala kaayam kodutha…aa…"
    ],
    thumbnail: require("../images/VellatuKannazhaghi.jpg")
  },
  {
    name: "Verasa Pogayilae Song Lyrics",
    title: "Verasa Pogayilae Song Lyrics",
    content: ["Singer: D. Imman",
  "Music by: D. Imman",
  "",
  "Male: {Verasa pogayilae..puthusa poravalae",
  "Ithu varaiyila kulir edukala pennaala",
  "Ava sirichathum thala oraiyuthu thannaala",
  "En pechu moochu enga kaanaala} (2)",
  "",
  "Male: Ithu naana enna..palasu ellam enga",
  "Pudhu sandhegangal undaaguthu",
  "Idhu thindaatama..illa thullaatama",
  "Manna vittu rendu kaal thaavuthu",
  "Eppothum naan pogum paadhai idhu",
  "Ippothu nirkaamal yen neeluthu",
  "En ullam lesaaga kai neeluthu",
  "Verasa pogaiyilae..puthusa poravalae",
  "",
  "Male: Nalla kachithama..enna pichu summa",
  "Thachu sekurathu un velaya",
  "Suttu vattarathil thantha pattam ellam",
  "Ippa nool aruntha kaathaadiya",
  "Nethoda nee vera naa veraya",
  "Eppo nee en nenjin mer kooraiya",
  "Ennullae nee paadhi naan meedhiya",
  "",
  "Male: Verasa pogayilae..puthusa poravalae",
  "Ithu varaiyila kulir edukala pennaala",
  "Ava sirichathum thala oraiyuthu thannaala",
  "En pechu moochu enga kaanaalaaaaaa.."
],
    thumbnail: require("../images/VerasaPogaiyila.jpg")
  },
  {
    name: "Kothani Kannala Song Lyrics",
    title: "Kothani Kannala Song Lyrics",
    content: [
     "Singers: M. L. R Karthikeyan and Anitha",
  "Music by: S. N. Arunagiri",
  "",
  "Female: Kothani kannaala enna",
  "Kothoda konnanae",
  "Utchaani kombethi enna",
  "Utkaara vechaanae",
  "",
  "Female: {Oru nellukkul enna",
  "Oliya vecha",
  "Umiya usura",
  "Parakka vecha} (2)",
  "",
  "Female: Sirikirenae sedhaiyurenae",
  "Unnoda nenapaala",
  "",
  "Male: Kothani kannaala enna",
  "Kothoda konnalae",
  "Utchaani kombethi enna",
  "Utkaara vechaalae",
  "",
  "Male: {Oru nellukkul enna",
  "Oliya vecha",
  "Umiya usura",
  "Parakka vecha} (2)",
  "",
  "Male: Sirikirenae sedhaiyurenae",
  "Unnoda nenapaala",
  "",
  "Female: Ada neeyum naanum onnu sera",
  "Nenthukitten saamikitta",
  "Namma kanava serthu selavazhikka",
  "Sollivechen manasukitta",
  "Aaaaaaa……aaahhh…..aahhh….aaa",
  "",
  "Male: Ada neeyum naanum onnu sera",
  "Nenthukitten saamikitta",
  "Namma kanava serthu selavazhikka",
  "Sollivechen manasukitta",
  "",
  "Male: Unna moochu mutta kaadhalichen",
  "Naanum thoongaama",
  "En buddhi ellam pedhalichu",
  "Kedukurenae medhakurenae",
  "Un pera marakaama",
  "",
  "Female: Kothani kannaala enna",
  "Kothoda konnanae",
  "Utchaani kombethi enna",
  "Utkaara vechaanae",
  "",
  "Female: Oru kodi jenmam onnuserndhu",
  "Vaazhanum mann mela",
  "Un moochu kaathu nenju thottu",
  "Pogudhu poo pola",
  "Aaaaaaa……aaahhh…..aahhh….aaa",
  "",
  "Male: Oru kodi jenmam onnuserndhu",
  "Vaazhanum mann mela",
  "Un moochu kaathu nenju thottu",
  "Pogudhu poo pola",
  "",
  "Male: Oru kadukum yennaiyum",
  "Pola kaadhal jodi illayadi",
  "Rendum onna serum neramvandhaa",
  "Onnu kodhikum onnu vedikkum",
  "Kaadhal idhu dhan de",
  "",
  "Female: Kothani kannaala enna",
  "Kothoda konnanae",
  "Male: Utchaani kombethi enna",
  "Utkaara vechaanae",
  "",
  "Female: Oru nellukkul enna",
  "Oliya vecha",
  "Umiya usura",
  "Parakka vecha" ],
    thumbnail: require("../images/KothaniKannala.jpg")
  },
  {name: "Kannum Kannum Nokia Song Lyrics",
    title: "Kannum Kannum Nokia Song Lyrics",
    content: [
      "Singers: Leslie Lewis, Andrea Jeremiah and Vasundhara Das",
  "Music by: Harris Jayaraj",
  "",
  "Female: ……………………………………",
  "",
  "Female: {Kannum kannum nokia",
  "Nee kollai kollum mafia",
  "Capuchino coffeeya sophia} (2)",
  "",
  "Male: Oo thermocol sirpam nee",
  "Unnil otti kondulla",
  "Chinna vellai pandhellaam naanadi",
  "",
  "Female: Mm thanneerin sirpam nee",
  "Kodai kaala dhaagam naan",
  "Unnai mondu nenjukul ootravaa",
  "",
  "Male: Vaa aiwa aiwa aiwa azhagae vaa vaa",
  "",
  "Female: Haa aiwa aiwa aiwa anbae vaa vaa",
  "",
  "Female: Kannum kannum nokia",
  "Nee kollai kollum mafia",
  "Capuchino coffeeya sophia",
  "",
  "Male: …………………………………..",
  "",
  "Male: Kaadhalar dhinathil pirandhen",
  "Kangalai pidithu nadandhen",
  "Oh idhayathil idari vizhundhen azhagaanen",
  "",
  "Female: Kaadhalin pugai padam ivanae",
  "Hollywood thirai padam ivanae",
  "America varai padam ivanae rasithenae",
  "",
  "Male: Ini kaadhalar top ten varisaiyilae",
  "Indha boomiyil naam thaan mudhalidamae o hoo",
  "Ini kaadhalar top ten varisaiyilae",
  "Indha boomiyil naam thaan mudhalidamae",
  "",
  "Female: O hoo oh remo oh remo oh remo",
  "Idhazhil thaa remo eeramo",
  "",
  "Male: Cool honey cool honey cool honey",
  "Idhazhil kudipen cool honey",
  "",
  "Female: Kannum kannum nokia",
  "Nee kollai kollum mafia",
  "Capuchino coffeeya toffeeya",
  "",
  "Male: Nokia sophia nokia tofeeya",
  "",
  "Male: …………………………",
  "",
  "Female: Cyanide cyanide vizhiyaal",
  "Mayakum poetic mozhiyaal",
  "Inika inika kollum kolaiyaali",
  "",
  "Male: Apple laptop pennae",
  "Madiyil vaithu unnai",
  "Viralgal theiya konji naan rasipenae",
  "",
  "Female: {Enai octopus viralgalaal suruti vitaai",
  "Oru atom bomb uyirukul uruti vitaai} (2)",
  "",
  "Male: Cool honey cool honey cool honey",
  "Idhazhil kudipen cool honey",
  "",
  "Female: Oh remo oh remo oh remo",
  "Idhazhil thaa remo eeramo",
  "",
  "Female: {Kannum kannum nokia",
  "Nee kollai kollum mafia",
  "Capuchino coffeeya sophia} (2)",
  "",
  "Male: Oo thermocol sirpam nee",
  "Unnil otti kondulla",
  "Chinna vellai pandhellaam naanadi",
  "",
  "Female: Thanneerin sirpam nee",
  "Kodai kaala dhaagam naan",
  "Unnai mondu nenjukul ootravaa",
  "",
  "Male: Aiwa aiwa aiwa azhagae vaa vaa",
  "",
  "Female: Haa aiwa aiwa aiwa anbae vaa vaa",
  "",
  "Male: Kannum kannum nokia",
  "Nee kollai kollum mafia",
  "",
  "Female: Capuchino coffeeya toffeeya",
  "",
  "Male: Nokia sophia nokia sophia",
  "Nokia sophia nokia sophia",
  "",
  "Female: Ahaan"
    ],
    thumbnail: require("../images/KannumKannum.jpg")
  },
  {name: "Paakathey Pakathey Song Lyrics",
    title: "Paakathey PakatheySong Lyrics",
    content: [
   "Singers: Pooja AV and Vijay Yesudas",
  "Music by: D. Imman",
  "",
  "Female: Paakadha paakadhaaa.. aiyaiyo paakadha",
  "Paakadha paakadha aiyaiyo paakadha",
  "Nee paatha parakura.. paatha marakura",
  "Pecha kuraikura satunuthaan",
  "Naan nekka sirikiren.. naaka kadikiren",
  "Sokkaa nadikiren patunuthaan",
  "Intha oru paarvaiyala thaanae naanum paazhaanen",
  "",
  "Male: Paakadha paakadhaaa.. aiyaiyo paakadha",
  "Nee paatha parakura.. paatha marakura",
  "Pecha kuraikura satunuthaan",
  "Naan nekka sirikiren.. naaka kadikiren",
  "Sokkaa nadikiren patunuthaan",
  "Intha oru paarvaiyala thaanae naanum paazhaanen",
  "",
  "Female: Paakadha paakadhaaa..", 
  "Male: Aiyaiyo paakadha",
  "",
  "Female: Oh eppo paaru unna nenachu",
  "Pacha pulla pola elachu",
  "",
  "Male: Kannukulla vachu paakum urava",
  "Ullavara unna parapen theliva",
  "",
  "Female: Chekka chevanthu naan pogum padithaan",
  "Thanna maranthu en paakura",
  "",
  "Male: Enna irukunnu enkitta nu",
  "Enna mulunga nee paakura",
  "",
  "Female: Intha oru paarvaiyaala thaanae naanum paazhaanen",
  "",
  "Male: Paakadha paakadhaaaaa..",
  "Female: Aiyaiyo paakadha..aa",
  "Male: Etti paatha enna theriyum",
  "Uthu paaru unmai puriyum",
  "",
  "Female: Thalli irunthu nee partha sariya",
  "Pakkathula vanthu paaren moraiyaaaahh.",
  "",
  "Male: Ennathuku enna paakuren nu",
  "Apa thitiputtu ponava",
  "",
  "Female: Katti kolla unna paakurenae",
  "Koora pattu eppo vanguvae",
  "",
  "Male: Intha oru paarvaiyaala thaanae naanum paazhaanen",
  "",
  "Female: Paakadha paakadha.aaa. aiyaiyo paakadha..",
  "Male: Nee paatha parakura.. paatha marakura",
  "Pecha kuraikura satunuthaan",
  "Female: Naan nekka sirikiren.. naaka kadikiren",
  "Sokkaa nadikiren patunuthaan",
  "Male and Female: Intha oru paarvaiyala thaanae naanum paazhaanaen",
  "Male: Paakadha paakadhaaa..",
  "Female: Ahhhh aiyaiyo paakadha.."  ],
    thumbnail: require("../images/PaakatheyPakathey.jpg")
  },
  {name: "UyirUruvaatha Song Lyrics",
    title: "UyirUruvaatha Song Lyrics",
    content: [  "Singers: Sathya Prakash and Chinmayi Sripada",
      "Music by: Sam CS",
      "",
      "Male: Haa…aaa",
      "Haa…aaa…aaa",
      "Haa…aaa…aa…aaa…aaa…",
      "Haa…aaa…aaa…",
      "",
      "Male: Uyir uruvaatha",
      "Urukulaikkatha",
      "Ennil vandhu sera",
      "Nee yosikkaadha",
      "",
      "Male: Dhisai ariyaatha",
      "Paravaiyapola",
      "Parakkavum aasa",
      "Unnodu dhoora",
      "",
      "Female: Vaazhkka theera theera",
      "Vaayen nizhalaa kooda",
      "Saagum dhooram poga",
      "Thunaiya neeyum theva",
      "Male: Naan un kooda",
      "",
      "Chorus: Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo",
      "Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo",
      "",
      "Female: Un nenappu",
      "Nenjukuzhivara irukku",
      "En ulagam muzhusum",
      "Unnai suththi suththi kedakku",
      "",
      "Female: Un nenappu",
      "Nenjukuzhivara irukku",
      "En ulagam muzhusum",
      "Unnai suththi suththi kedakku",
      "",
      "Female: Manasula oruvidha validhaan",
      "Sugama sugama",
      "Enakkula urukkura unna neeyum",
      "Nejama nejama",
      "",
      "Female: Kannae kannae",
      "Kaalam dhorum",
      "Enkooda nee mattum",
      "Podhum podhum",
      "Nee naalum",
      "",
      "Chorus: Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo",
      "Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo",
      "",
      "Male: Naan muzhusa",
      "Unnai enakkula podhachen",
      "En usura azhagae",
      "Unna nitham nitham nenachen",
      "",
      "Male: Naan muzhusa",
      "Unnai enakkula podhachen",
      "En usura azhagae",
      "Unna nitham nitham nenachen",
      "",
      "Male: Ini varum jenmam mottham",
      "Neeyum dhaan oravaa varanum",
      "Marupadi unakkena pirandhidum",
      "Varam naan peranum",
      "",
      "Male: Pennae pennae",
      "Vaazhka neela",
      "En kuda nee mattum",
      "Podhum podhum",
      "Nee naalum",
      "",
      "Chorus: Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo",
      "Ohoo..oo..hoho",
      "Ohoo..oo..hoho",
      "Hoho..hoho..hoho…hoooo"
    
    ],
    thumbnail: require("../images/UyirUruvaatha.jpg")
  },
  {name: "Ayyo Adi Aathe Song Lyrics",
    title: "Ayyo Adi Aathe Song Lyrics",
    content: [ "Singers: Vandhana Srinivasan and Jagathish",
      "Music by: N. R. Raghunanthan",
      "",
      "Male: Ayyo adi aathae",
      "En kannu kaathu mookkae",
      "Kondu pora nee thaan",
      "En manasa.. en manasa..",
      "",
      "Female: Yetti ninnu paathen",
      "Nee enga vacha nethae",
      "Kothi pora nee thaan",
      "En vayasa.. en vayasa..",
      "",
      "Male: Yettam number polathaan",
      "Suthi vandhu valaichaalae",
      "",
      "Female: Kattam katti en nenappa",
      "Patha vachi poraanae",
      "",
      "Male: Ava kenda kaalu",
      "Sunda vaikkum",
      "En usurathaan",
      "Ava sandai podum",
      "Kannu rendum",
      "En ulagandhaan",
      "",
      "Male: Ayyo adi aathae",
      "En kannu kaathu mookkae",
      "Kondu pora nee thaan",
      "En manasa.. en manasa..",
      "",
      "Male: Ava segappu sembaruthi pola",
      "Ava sirippu senggarumba pola",
      "Ava pechu senthamizha pola",
      "Inikkum.. inikkum..",
      "",
      "Female: Avan morappu sandiyara pola",
      "Avan vanappu mammuthana pola",
      "Avan nenappu nenjukkulla thenamum",
      "Ilukkum.. ilukkum..",
      "",
      "Male: Kundoosi paarvakkaari",
      "Kundu vaikkum pechukaari",
      "Kuthukallaa nikka vaikkum",
      "Kummiruttu machakkaari",
      "",
      "Male: Ava kenda kaalu",
      "Sunda vaikkum",
      "En usurathaan",
      "Ava sandai podum",
      "Kannu rendum",
      "En ulagandhaan",
      "",
      "Male: Ayyo adi aathae",
      "En kannu kaathu mookkae",
      "Kondu pora nee thaan",
      "En manasa.. en manasa..",
      "",
      "Female: Hmm..mmm…mmmm",
      "Hmm..mmm…mmm…",
      "Mmm….mmmm..mmmm….mmmmm",
      "Mmm….mmmm..mmmm….mmmmm",
      "",
      "Female: Avan kooda jenmathukkum vaazhuven",
      "Avan irundha eppadi naan saaguven",
      "Avan sirikka enna venaa pannuven",
      "Naandhaan.. naandhaan..",
      "",
      "Male: Ava kannil thoosi onnu vilundhaa",
      "Athanaala ava kannu kasinja",
      "Kaaththa naanum katti vachu midhippen",
      "Nesandhaan.. nesandhaan..",
      "",
      "Female: Enakinnu porandhaan paaru",
      "Enakkulla pugundhaan paaru",
      "Nenappellaam kalandhaan paaru",
      "Avan than en usurukku veru",
      "",
      "Male: Ava kenda kaalu",
      "Sunda vaikkum",
      "En usurathaan",
      "Ava sandai podum",
      "Kannu rendum",
      "En ulagandhaan",
      "",
      "Male: Ayyo adi aathae",
      "En kannu kaathu mookkae",
      "Kondu pora nee thaan",
      "En manasa.. en manasa..",
      "",
      "Female: Yetti ninnu paathen",
      "Nee enga vacha nethae",
      "Kothi pora nee thaan",
      "En vayasa.. en vayasa.."
    ],
    thumbnail: require("../images/Ayyoadi.png")
  }, 
  {name: "Jing Chikkan Song Lyrics",
    title: "Jing Chikkan Song Lyrics",
    content: ["Singers: Magizhini and Puspha Vanam Kuppuswamy",
  "Music by: Devi Sri Prasad",
  "",
  "Female: Akka maare anna maare",
  "Aiya maare aatha maare",
  "Orru kanam namma Ore",
  "",
  "Male: Jing chikaan jing chikaan",
  "",
  "Female: Maama maare machaan maare",
  "Machinichi naathanare",
  "Pakanaum enna pakathoorae",
  "",
  "Male: Jing chikaan jing chikaan",
  "",
  "Male: Yappa seekarama molatha adingapa..",
  "",
  "Male: Adiye thaaru maara thaavura mosalu",
  "En nenjukulla ninnukittu oothura visulu",
  "",
  "Male: {Jing chikaan jing chikaan jing chikaan jingidichakkan} (2)",
  "",
  "Male: Kumichu konda potta koovura kuyilu",
  "En thandavaalam gandamaaga otura raiyilu..",
  "",
  "Male: {Jing chikaan jing chikaan jing chikaan jingidichakkan} (2)",
  "",
  "Female: Kurumbu paiya pulla..kurumbu paiya pulla",
  "Kennathu kulla vanthu kappalvidatha",
  "Thiruttu paiya pulla..thiruttu paiya pulla",
  "Thorantha veetukulla kannam podatha",
  "",
  "Male: Un kaal patta mann alli paakaittil vechuruken",
  "Kandukaatha kambi neetatha",
  "",
  "Female: Mama ippadi konjuthey yenma ippadi minjura (Dialogue)",
  "",
  "Female: Aiyayo ambala ice vandi pola",
  "Ada ice veche ice veche kavuthuduvaan girlla",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Female: Valathu kanirukkum pennoruthi mela",
  "Ada edathu kannu meyumappa innoruthi mela",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Male: Pullaiyar koyil kozhukatta pola",
  "Nee kannam rendu vechurukka kazhuthuku mela",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Male: Ada aduppu mel vecha paal chetti pola",
  "Nee pongurutha paathu paathu poonaiyachu moola",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Female: Azhagu paiya pulla..azhagu paiya pulla",
  "Valaiya viruchutu kaathirukaatha",
  "",
  "Male: Un kaal vella kai vella",
  "Paarthathum peche varala..",
  "Pappa peepee paa paa poooo..",
  "",
  "Female: Aiyo pechu moochu illama kedakaan",
  "Ethanu parthu seiyen (Dialogue)",
  "",
  "Female: Vaai ilaa poochinu paavam paatha pochu",
  "Ivan mutha kathi vechu enna keechuduvaan keechu",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Female: Ora kannaala pakura saatchi",
  "Ithu thappana paarva en thaavani saatchi",
  "",
  "Male: Ada santhanam saarayam senthuta kalava",
  "Un saayalil pathendi eluettu nelava",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "Male: Idupil somakura vaanavil valava",
  "Naan engeyum paakalaye ippadi patta alava",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Female: Kirukku paiya pulla",
  "Kirukku paiya pulla",
  "Kuruku vazhiyila seena podaatha",
  "",
  "Male: Hey kazhuvura meenula nazhuvura meenapola",
  "Kaiyavittu thulli odaatha",
  "",
  "Female: Adi kena siruki un manasu enna kalla? (Dialogue)",
  "",
  "Female: Ada manasula vechuruken ambuttu aasa",
  "Ada koocham vanthu thadukuthu vaai vittu pesa",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan",
  "",
  "Male: Adiye usura pesaiyithu nee sirukum osa",
  "Ada unna vechu nenjukulla seiyuren poosa..",
  "",
  "Male: Jing chikaan jing chikaan jing chikaan jingidichakkan"
    ],
    thumbnail: require("../images/Jingchakkan.jpg")
  },
  {name: "Naana Thaana Song Lyrics",
    title: "Naana Thaana Song Lyrics",
    content: [  "Singer: Anirudh Ravichander",
      "Music by: Anirudh Ravichander",
      "",
      "Chorus: Oru pattamboochiya utta paaruda",
      "Ettadha dhoorathula",
      "Oru pattamboochiya utta paaruda",
      "Ettadha dhoorathula",
      "",
      "Male: Hey naana thaana veena ponaa",
      "Sariyae illayae",
      "Ada aana oona… kaana ponaa",
      "Vazhiyae illayae",
      "",
      "Male: Oru kutti size-u",
      "Buss-u vaanam koluthi",
      "Nenju naduvula niruthitta oruthi",
      "Oru pattamboochiya utta paaruda",
      "Ettadha dhoorathula",
      "",
      "Male: Oru kattu koppanavana",
      "Dhaan kadathi",
      "Nenja dhoosi thatti eduthu dhaan niruthi",
      "Ippo nera ulla vandhu dera poda pora",
      "Dhaaralama oruthi",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee… andha kaanaala paakura",
      "Saakkulla thaakaadha",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee…aeee……..",
      "Kaanaala thaakaadha",
      "",
      "Male: Hey naana thaana..huh..huh..",
      "Naana thaana veena ponaa",
      "Sariyae illayae",
      "Ada aana oona… kaana ponaa",
      "Vazhiyae illayae",
      "",
      "Male: Kitta thatta keranguren",
      "Keela eranguren",
      "Konjam kolambi tholayuren",
      "",
      "Male: Edaagooda nelivaiyum",
      "Ava polivayyum",
      "Paathu polambi tholayuren",
      "",
      "Male: Summavae sirikkirenn…",
      "Summavae sirikkirenn",
      "Mela parakkuren",
      "Neja vayasa marakkurenn",
      "",
      "Male: Konaala dhaan nadakkuren",
      "Kollam kirukuren",
      "Aana manasa maraikkuren..aann..aann…",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee… andha kaanaala paakura",
      "Saakkulla thaakaadha",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee…aeee…..",
      "Kanaala thaakaadha",
      "",
      "Male: Hey naana thaana..huh..huh..",
      "Naana thaana veena ponaa",
      "Sariyae illayae",
      "Ada aana oona… kaana ponaa",
      "Vazhiyae illayae",
      "",
      "Male: Oru kutti size-u",
      "Buss-u vaanam koluthi",
      "Nenju naduvula niruthitta oruthi",
      "Oru pattamboochiya utta paaruda",
      "Ettadha dhoorathula",
      "",
      "Male: Oru kattu koppanavanana",
      "Dhaan kadathi",
      "Nenja dhoosi thatti edthu dhaan niruthi",
      "Ippo nera ulla vandhu dera poda pora",
      "Dhaaralama oruthi",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee… andha kaanaala paakura",
      "Saakkulla thaakaadha",
      "",
      "Male: Adiyaeee.. munnala porava",
      "Pinnaalaa paakaadha",
      "Azhagaeee…aeee………",
      "Kanaala thaakaadha",
      "",
      "Male: Adiyaeee…. azhagaeee…"
    
    ],
    thumbnail: require("../images/Naanathaana.jpg")
  },
  {name: "Adiye Unna Paathida Song Lyrics",
    title: "Adiye Unna Paathida Song Lyrics",
    content: ["Singer: Sathya Prakash and Vandhana",
  "Music by: D. Imman",
  "",
  "Male: Adiyae unna paathida paathida naan kolanjenaee…",
  "Azhaga intha aaradi aambalayum velanjenaeeee..",
  "Pozhuthum un vaasana aasaya kootuthae",
  "Adanga mathayanai pol ena thaakuthae",
  "Usurae un oora paarva sakaratha nenjukulla sutha viduthaeee…",
  "",
  "Male: Adiyae unna paathida paathida naan kolanjenaee…",
  "Azhaga intha aaradi aambalayum velanjenaeeee..",
  "",
  "Female: Ethukku.. ennai nee.. pora yera oothura",
  "Surukku kaiyura vizhayala maathura",
  "",
  "Male: Munnazhagil nee thaan murukera jaada kaatura",
  "Otha noodi kuda othungama theeya mootura",
  "",
  "Female: Engo ethum neeyaga un nenapu theeyaga",
  "Pudichen pudichen nenjil aani adichen",
  "",
  "Male: Adiyae unna paathida paathida naan kolanjenaee…",
  "",
  "Male: Una naan.. nencha.. thimiraagi poguren",
  "Velakku thiri naan vidi velli aguren",
  "",
  "Female: Ethanaiyo vaartha therinjaalum vaaya mooduren",
  "Otha pana ola athu pola naanum oduren",
  "",
  "Male: Sithathula nooyaga mothathula thaayaga",
  "Kedacha kedacha enna yendi kelacha",
  "",
  "Male: Adiyae unna",
  "Female: Paathida paathida naan kolanjenaee…",
  "Female: Azhaga",
  "Male: Intha aaradi aambalayum velanjenaeeee..",
  "",
  "Female: Pozhuthum un vaasana aasaya kootuthae",
  "Adanga mathayanai pol ena thaakuthae",
  "Usurae un oora paarva sakaratha nenjukulla sutha viduthaeee…eeehh"
    ],
    thumbnail: require("../images/AdiyeUnnaPaathida.jpeg")
  },
  {name: "Thakkaalikku Thavaniya Song Lyrics",
    title: "Thakkaalikku Thavaniya  Song Lyrics",
    content: [
      "Singer: Renu Kannan and Vijay Yesudas",
  "Music by: Yuvan Shankar Raja",
  "",
  "Male: Thakkalikku thaavaniya",
  "Pottu vida naa varataa",
  "Female: Mukkalikku mutti thencha",
  "Muttu thara naa varataa",
  "",
  "Male: Aatukallu iduppaal",
  "Enna araikiriyae poruppa",
  "Female: Seemathanni sirippaal",
  "Enna patha vaikuthu karuppa",
  "",
  "Male: Nenchukuzhikulla intha payabulla",
  "Innaiku thaan maatikittaan",
  "Female: Patta pagalula vetta veliyila",
  "Vekka pada vachuputtaan",
  "",
  "Male: Thakkalikku thaavaniya",
  "Pottu vida naa varataa",
  "Female: Mukkalikku mutti thencha",
  "Muttu thara naa varataa",
  "",
  "Male: Paththu ooru pasiya pokkum",
  "Azhagu azhagu",
  "Female: Oh.. pakkuvama paaya pottu",
  "Pazhagu pazhagu",
  "",
  "Male: Nee aasa velaiyum nelama",
  "Velanchu nikkira vazhama",
  "Female: Nee kaala suththum paamba",
  "Kavuthuppottu kuthuriyae vemba…",
  "",
  "Male: Thakkaliku thakkaliku thakkaliku..",
  "",
  "Male: Thakkalikku thaavaniya",
  "Pottu vida naa varataa",
  "Female: Mukkalikku mutti thencha",
  "Muttu thara naa varataa",
  "",
  "Male: Hey aatukallu iduppaal",
  "Enna araikiriyae poruppa",
  "Female: Seemathanni sirippaal",
  "Enna patha vaikuthu karuppa",
  "",
  "Male: Vellam vadiyala",
  "Solla mudiyala",
  "Thathalichu saaguran di",
  "Female: Nandu valaiyila",
  "Gundu podura nee",
  "Rendu pattu veguran da",
  "",
  "Male: Maligappo vaasam veesum",
  "Moochu moochu",
  "Female: Panavellam paalil kalantha",
  "Pechu pechu",
  "",
  "Male: Un kuruvi koodu konda",
  "Poda solluthae sanda",
  "Female: Un mookil sevantha molaga",
  "Athari sethari patharavaikuthae",
  "Enna…",
  "",
  "Male: Aaa thakkaliku thakkaliku",
  "Thakkaliku..heyyy",
  "",
  "Male: Thakkalikku thaavaniya",
  "Pottu vida naa varataa",
  "Female: Mukkalikku mutti thencha",
  "Muttu thara naa varataa",
  "",
  "Male: Aatukallu iduppaal",
  "Enna araikiriyae poruppa",
  "Female: Seemathanni sirippaal",
  "Enna patha vaikuthu karuppa",
  "",
  "Male: Vellam vadiyala",
  "Solla mudiyala",
  "Thathalichu saaguran di",
  "Female: Nandu valaiyila",
  "Gundu podura nee",
  "Rendu pattu veguran da"
    ],
    thumbnail: require("../images/Thakkaalikuthavaniya.jpg")
  },
   {name: "Pasappukkalli Song Lyrics",
    title: "Pasappukkalli Song Lyrics",
    content: [ "Singers: Nivas K. Prasanna, Vijay Antony, and Alex Samuel Jenito",
      "Music by: Nivas K. Prasanna",
      "",
      "Male: Achchu asalu vennilaava",
      "Bhoomiyila paathathundaa",
      "Pachcha pasum pullu onnu",
      "Aaradiyil valarnthathundaa",
      "",
      "Male: Illaennu solla mudiyaathu",
      "Avala paaththa munnaala",
      "Poi solla mudiyaathu",
      "Avala paaththa munnaala",
      "Poi solla mudiyaathu",
      "",
      "Chorus: {En pasappukkalli en pasappukkalli",
      "Ava thandhupputtaa ivan manasa alli",
      "En erukkanjulli en erukkanjulli",
      "Ava paththa vachaa ivan nenappa killi} (2)",
      "",
      "Male: Keelanelli kannu nenjaa",
      "Keelaththalli pogum",
      "Vaadaaamalli vaasam aala",
      "Vaazha solli pogum",
      "",
      "Chorus: {En nesamalli en nesamalli",
      "En paasavilli en paasavilli} (2)",
      "Hooo oo hooo oo ooo",
      "",
      "Chorus: {Thaana naana naa nana naa",
      "Nana naa naa naa naa naa} (2)",
      "Hey hey hey hey hey hey hey hey",
      "",
      "Male: Nongu kondai pinnalagu",
      "Sundi vachi solattuthappaa",
      "Male: Adengappa",
      "",
      "Male: Sevvelani munnalagu",
      "Nondi aada vaikkuthappa",
      "Male: Vaikkuthappa",
      "",
      "Male: Ava ..panamaramaa",
      "Thennamaramaa theriyaliyae",
      "Male: Theriyaliyae",
      "Male: Enna naanum solla",
      "Ippo puriyaliyae",
      "Male: Puriyaliyae",
      "Male: Enna naanum solla",
      "Ippo puriyaliyae",
      "",
      "Male: En aasa rossaa",
      "Chorus: Aasa rossaa",
      "Male: Naan aanen loosa",
      "Chorus: Aanen loosa",
      "Male: Naan ponen thoosaa",
      "Chorus: Ponen thoosaa",
      "Male: Naan odanjen peesaa",
      "Chorus: Odanjen peesaa",
      "",
      "Chorus: En aasa rossaa",
      "Aanen loosa",
      "Ponen thoosaa",
      "Odanjen peesaa",
      "Rosaa rosaa rosaa rosaa",
      "Ro ro ro ro ro ro roo ooo",
      "",
      "Male: Nenjukulla pootta pottu",
      "Vechchikkuven vaadi",
      "Onnodaiyaa nizhala serthu",
      "Thachchikkuven naandi",
      "",
      "Male: {Onn kosuvaththula",
      "Naan mayangurendi",
      "Oru kosuvaattam",
      "Kannu mulikkurendi} (2)",
      "",
      "Chorus: ………………………..",
      "",
      "Chorus: En aasa madhuvae nee dhaan",
      "Onna paatha piragu naan dhaan",
      "Adi aanen paaru thean dhaan",
      "Nee vilagi pona veen dhaan",
      "",
      "Male: Uththu parkkum kannu rendum",
      "Karuppu vella gundumalli",
      "Moochu kaathu enna thottu",
      "Poguthadaa pera solli",
      "",
      "Male: Pesi pogum varthai ellaam",
      "Kokkippodum kodukaapuli",
      "Paathu pogum paarvai ellam",
      "Paththa vaikkum kirukaa thalli",
      "",
      "Male: Ne vecha pottu",
      "Ennai vattamittu",
      "Nenja suttu thalli poguthadi",
      "Thaviyaa thavichen",
      "",
      "Male: Ava maiyiruttu",
      "Adi machcha mottu",
      "Ennai thottu killi ooduthadi",
      "Thaniyaa sirichen",
      "",
      "Chorus: Vettaveli, oththavali",
      "Vandhaa vali.. pona vali",
      "Konjum kili, kollum uli..",
      "Kannu muli… kannakkuzhi",
      "Retta suzhi..pinju mozhi",
      "Nenja kili… anbu thuli",
      "Enna solli yethu solli",
      "Piththukkuli polamburendiii…",
      "Salamburendiii…",
      "Nenappaaala vaanathukku",
      "Kelamburen naaan",
      "Di di di di di…",
      "",
      "Male: Pasappukkalli pasappukkalli",
      "Pasappukkalli heyy",
      "Pasappukkalli pasappukkalli",
      "Pasappukkalli heyy",
      "",
      "Male: {En pasappukkalli en pasappukkalli",
      "Vandhu aadiputta oru aadupuli",
      "En yerukkanjuli en yerukkanjuli",
      "Naan maattikkiten oru veettu eli…..",
      "",
      "Male: Adiyae….hoo… oo…hooo",
      "Adiyae…Lalalalaaa..lalala…",
      "Lala laalaa laa laa laa",
      "Hey lalalalaaa..lalala…",
      "Lala laalaa laa laa laa…aa….."
    ],
    thumbnail: require("../images/Pasappukkalli.jpg")
  },
  {name: "Maduraikku Pogathadi Song Lyrics",
    title: "Maduraikku Pogathadi Song Lyrics",
    content: ["Singers: Benny Dayal, Archith, and Darshana KT",
  "Music by: A.R. Rahman",
  "",
  "Chorus: Karpoora kannigaiyae vaaraai",
  "Adi alanthu alanthu nayanthu nayanthu paaraai",
  "Nee vanghala maharaaniyae",
  "Valathu kaal eduthu vaaraai neeyae",
  "",
  "Nee vantha idam valamaaga",
  "Sendra idam vanamaaga",
  "Serntha idam sugamaaga",
  "Vaazha pora",
  "",
  "Male: Maduraikku pogathadi",
  "Anga malli poo kanna vekkum",
  "Thanjaavur pogaathadi",
  "Thala aataama bomma nikkum",
  "",
  "Male: Thoothukudi pona sila kappal kara thattum",
  "Kodaikaanal pona anga megam unna suthum",
  "",
  "Chorus: {Asaruthu asaruthu orr mothamaa",
  "Athu enna athu enna un kuthamaa} (2)",
  "",
  "Chorus: Karpoora kannigaiyae vaaraai",
  "Adi alanthu alanthu nayanthu nayanthu paaraai",
  "Nee vanghala maharaaniyae",
  "Valathu kaal eduthu vaaraai neeyae",
  "",
  "Male: Adi othaiyila thaniyaaga",
  "Methaiyila thoongaathae",
  "Akka magan vaaraandi",
  "Alaichu pogha",
  "",
  "Male: Maduraikku pogathadi",
  "Anga malli poo kanna vekkum",
  "",
  "Chorus: Sithira naa …veyiladikkum",
  "Kaarthiga naa ….mazhaiyadikkum",
  "Adaar pudaar kadaar thadaar",
  "Maapillai thaan thangam",
  "",
  "Chorus: Aadiyinaa…kaathadikkum",
  "Maargazhi naa.. ha ha ha",
  "Damaal damaal gabaal gabaal",
  "Maapillai thaan singam",
  "",
  "Male: Ho…maruthaani thotathukkae",
  "Ada maruthaani yaaru vecha",
  "Ho.. thera thera iva vaara vaara",
  "",
  "Female: Woh.. kaatu kuyilum kattika thaan",
  "Thamizh naatu puyalum vanthuruchae",
  "Hoy… jora jora varum veera veera",
  "",
  "Male: Naan akaraiyil irunthaalum",
  "Ikkaraiyil irunthaalum",
  "Sakaraiyaa irupalae aasaiyalae",
  "",
  "Male: Maduraikku pogathadi",
  "Anga malli poo kanna vekkum",
  "",
  "Chorus: Asaruthu asaruthu orr mothamaa",
  "Athu enna athu enna un kuthamaa",
  "Marumaga marumaga vanthachamma",
  "Eni maamiyaar pathavithaan unakaachamma",
  "",
  "Chorus: Thamizh naatu manmathanae vaaraai",
  "Pen mayanga mayanga nadanthu nadanthu vaaraai",
  "Nee indira maharaajanae",
  "Vetri maalaikena piranthavanae",
  "",
  "Chorus: Nee thotathellaam jeyamaaga",
  "Sonnathellaam nijamaaga",
  "Kanni nila vanthiduchu",
  "Kanavu kaana…",
  "",
  "Female: Ho…ketti melam naathaswaram",
  "Atha sernthu ketkum neram sugam",
  "Dum dum dum dum",
  "Du dudududu dum dum dum dum",
  "",
  "Male: Ho… manjal kunguma thaaliyin sirappu",
  "Pengalukellaam inoru porappu",
  "",
  "Female: Dum dum dum dum",
  "Male: Dum dum dum dudum dudum",
  "Dum dum dum dum…",
  "Female: Wohoo…hooohoo",
  "",
  "Female: Chandiranil oru paathi",
  "Indiranil oru paathi",
  "Sundaranae en jodi aanathenna",
  "",
  "Male: Maduraikku pogathadi",
  "Anga malli poo kanna vekkum",
  "",
  "Female: Maduraikku pogamaaten",
  "En malli poo un kaiyilae",
  "",
  "Male: Thanjaavur pogathadi",
  "Thala aataama bomma nikkum",
  "",
  "Female: Engum poga maaten",
  "Un munnaala thaan nippen",
  "Munnaal vanthu ninnu",
  "En kannaal sokka vaipen",
  "",
  "Chorus: {Asaruthu asaruthu orr mothamaa",
  "Athu enna athu enna un kuthamaa} (4)"
    ],
    thumbnail: require("../images/Maduraikkupogathadi.jpg")
  },
  {name: "Sollitaaley Ava Kaadhala Song Lyrics",
    title: " Sollitaaley Ava Kaadhala Song Lyrics",
    content: ["Singers: Ranjith and Shreya Ghoshal",
  "Music by: D. Imman",
  "",
  "Male: Sollitalae ava kaadhala",
  "Sollum podhae sugam thaalala",
  "Ithu pol oru vaarthaiya yaaridamum nenju kekala",
  "Ini veroru vaarthaiya ketidavum enni paakala",
  "Ava sonna sollae pothum",
  "Athukeedae illaa yethum.. yethum",
  "",
  "Female: Sollitenae iva kaadhala",
  "Sollum podhae sugam thaalala",
  "Ithu pol oru vaarthaiya yaaridamum solla thonala",
  "Ini veroru vaarthaiya pesidavum ennam kudala",
  "Unathanbae ondrae pothum",
  "Athukeedae illai yethum.. yethum.. mm",
  "",
  "Male: Ammaiaval sonna sol kekala",
  "Appanavan sonna sol kekala",
  "Unnodaya solla keten",
  "Rendu pera onna parthen",
  "",
  "Female: Manasayum thoranthu sonna",
  "Ellaamae kidaikuthu ulagathula",
  "Varuvatha eduthu sonna",
  "Santhosam mulaikuthu idhayathula",
  "",
  "Male: Ada sonna sollae pothum",
  "Athukeedae illai yethum.. yethum..",
  "",
  "Female: Sollitenae iva kaadhala",
  "Male: Sollitalae ava kaadhala",
  "",
  "Female: Ethanayo sollu sollamalae",
  "Ullathilae undu enbaargalae",
  "Sollurathil paathi inbam",
  "Sonna pinnae yethu thunbam",
  "",
  "Male: Uthatula irundhu sonna",
  "Thannaale maranthidum nimishathula",
  "Idhayathil irundhu sonna",
  "Pogama nilachidum uthirathula",
  "",
  "Male: Ava sonna sollae pothum",
  "Athukeedae illai yethum.. yethummm..",
  "",
  "Female: Sollitenae iva kaadhala",
  "Sollum podhae sugam thaalala",
  "Ithu pol oru vaarthaiya yaaridamum solla thonala",
  "Ini veroru vaarthaiya pesidavum ennam kudala",
  "Unathanbae ondrae pothum",
  "Atharkeedae illai yethum yethum … yethumm..",
  "",
  "Mmm mmmhmm mmmhmm"
    ],
    thumbnail: require("../images/Sollitaale.jpg")
  },
  {name: "Un Paarvaiyil Paithiyam Song Lyrics",
    title: "Un Paarvaiyil Paithiyam Song Lyrics",
    content: ["Singers: Karthik and Sumangali",
  "Music by: Devi Sri Prasad",
  "",
  "Male: Hmm.. unn paarvayil payithiyam aanen",
  "Un varthaiyil vaakiyam aanen",
  "Un vetkathai vedikai parthen",
  "Mayanginen",
  "",
  "Male: Oru nyabaga alai ena vanthu",
  "En nenjinai nanaithaval neeyae",
  "En vaaliba thimirinai unnal maatrinen",
  "",
  "Male: Pennaga irunthaval unnai",
  "Naan indru kaadhal seithen",
  "Unnoda arimugathalae",
  "Naan unnil maraimugam aanen",
  "Narambellam isaimeeta",
  "Kuthithen naanae",
  "",
  "Male: La la laila lailai lae",
  "La la lailai lae",
  "Lai la lai lai lae lai la lai lai lae lailalae",
  "",
  "Male: Hey.. unn paarvayil payithiyam aanen",
  "Un varthaiyil vaakiyam aanen",
  "Un vetkathai vedikai parthen",
  "Mayanginen",
  "",
  "Male: Haan ethu ithuvo… ethu ithuvo",
  "Un mounam solgindra",
  "Ezhuthilla oosaigal",
  "Yenendru naan soluven",
  "",
  "Female: Ithu athuvo..",
  "Male: Hmmm…",
  "Ithu athuvoo…",
  "Male: Hmm…",
  "Sollatha solluku",
  "Illatha varthaiku",
  "Yethetho arthangalae",
  "",
  "Male: Penn thozhan naan",
  "Aan thozhi nee",
  "Natpukul nam kaadhal vazhum",
  "",
  "Female: Aan aasai naan",
  "Penn aasai nee",
  "Asaigal peraasaithan",
  "",
  "Male: La la laila lailai lae",
  "La la lailai lae",
  "Lai la lai lai lae lai la lai lai lae lailalae",
  "",
  "Male: Unn paarvayil payithiyam aanen",
  "Un varthaiyil vaakiyam aanen",
  "Un vetkathai vedikai parthen",
  "Mayanginen",
  "",
  "Female: Unatharugae irupathanal",
  "Iravuku theriyatha",
  "Pagaluku puriyatha",
  "Pozhuthondrai nee kaatinai",
  "",
  "Male: Idhayathil nee irupathanal",
  "Naan thoongum neerathil",
  "Enulae thoongamal",
  "Nenjukul vayadinai",
  "",
  "Female: Kannadi nee",
  "Gadigaram naan",
  "Unulae oododi vazhven",
  "",
  "Male: Kaadhal ennum",
  "Kaduthasi nee",
  "Endrendrm anbudan naan",
  "",
  "Male: La la laila lailai lae",
  "La la lailai lae",
  "Lai la lai lai lae lai la lai lai lae lailalae",
  "",
  "Whistling: ……………………………"
    ],
    thumbnail: require("../images/UnPaarvaiyil.jpg")
  },
  {name: "Un Paarvaiyil Vizhuntha Song Lyrics",
    title: "Un Paarvaiyil Vizhuntha Song Lyrics",
    content: ["Singers: Anirudh Ravichander and Vivek Siva",
  "Music by: Anirudh Ravichander",
  "",
  "Male: Un Paarvayil vizhundha",
  "Naal mudhal",
  "En thunbangal",
  "Marandhu ponadhu",
  "Un kaiviral sera thudikkudhu",
  "Anbae anbae",
  "",
  "Male: Un Paarvayil vizhundha",
  "Naal mudhal",
  "En thunbangal",
  "Marandhu ponadhu",
  "Un kaiviral sera thudikkudhu",
  "Anbae anbae",
  "",
  "Male: Anbae anbae",
  "Anbae anbae"
    ],
    thumbnail: require("../images/UnPaarvaiyilVizhuntha.jpg")
  }

];

export default articles;
